config/routes.rb
Rails.application.routes.draw do
  get "genres/index"
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Корневой маршрут
  root "home#index"

  # Маршруты для HomeController
  get 'genres', to: 'home#genres'
  get 'legends', to: 'home#legends'

  # Маршрут для регистрации
  # get 'signup', to: 'users#new', as: :signup
  # post 'signup', to: 'users#create'
  get "/", to: "home#index"

  get "/signup", to: "users#signup"
  get "/login", to: "users#login"
  get "/dashboard", to: "users#dashboard"
  get "/logout", to: "users#logout"
  
  post '/signup', to: 'users#signup'
  post "/login", to: 'users#login'
  post 'logout', to: 'users#logout'

  # Контактная форма
  get 'contact', to: 'contacts#contact', as: 'contact'
  post 'submit_message', to: 'contacts#create', as: 'submit_message'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/legend.rb
class Legend < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, length: { minimum: 6 }
end

app/controllers/HomeController.rb
class HomeController < ApplicationController
  def index
  end

  def genres
    @genres = Genre.all
  end

  def legends
    @legends = Legend.all
  end

  def contact
  end

  def regist
  end

end

app/controllers/UsersController.rb
class UsersController < ApplicationController
  def signup
    if request.get?
      flash[:error] = nil
    elsif request.post?
      email = params[:email]
      password = params[:password]

      uri = URI(ENV['FIREBASE_SIGNUP'])
      body = { email: email, password: password, returnSecureToken: true }
      res = Net::HTTP.post(uri, body.to_json, "Content-Type" => "application/json")
      data = JSON.parse(res.body)

      if res.is_a?(Net::HTTPSuccess)
        session[:id_token] = data['idToken']
        session[:user_id] = data['localId']
        flash[:notice] = "Регистрация прошла успешно!"
        redirect_to login_path
      else
        flash[:error] = translate_error(data["error"]["message"])
        render :signup
      end
    end
  end

  def login
    if request.get?
      flash[:error] = nil
    elsif request.post?
      email = params[:email]
      password = params[:password]

      uri = URI(ENV['FIREBASE_LOGIN'])
      res = Net::HTTP.post_form(uri, 'email' => email, 'password' => password)
      data = JSON.parse(res.body)

      if res.is_a?(Net::HTTPSuccess)
        session[:user_id] = data['localId']
        session[:id_token] = data['idToken']
        flash[:notice] = "Вход выполнен успешно!"
        redirect_to root_path
      else
        flash[:error] = translate_error(data['error']['message'])
        render :login
      end
    end
  end

  def dashboard
    # Получение ID текущего пользователя
    user_id = session[:user_id]
    id_token = session[:id_token]

    Rails.logger.debug "Dashboard: User ID - #{user_id}, ID Token - #{id_token}"

    # Проверка наличия user_id и id_token
    if user_id.nil? || id_token.nil?
      flash[:error] = "Ошибка сессии. Пожалуйста, войдите снова."
      redirect_to login_path and return
    end

    # Получение данных пользователя из Firebase Authentication
    begin
      url = URI("#{ENV['FIREBASE_AUTH_URI']}/accounts:lookup?key=#{ENV['FIREBASE_API_KEY']}")
      Rails.logger.debug "Firebase Auth URI: #{url}"
      response = Net::HTTP.post(
        url,
        { idToken: id_token }.to_json,
        { "Content-Type" => "application/json" }
      )
      Rails.logger.debug "Response code: #{response.code}"
      Rails.logger.debug "Response body: #{response.body}"
      data = JSON.parse(response.body)

      if response.code.to_i == 200
        @user = data["users"].find { |u| u["localId"] == user_id }
        flash[:error] = "Пользователь не найден." if @user.nil?
      else
        flash[:error] = "Не удалось загрузить данные пользователя."
        Rails.logger.error "Firebase error: #{response.body}"
      end
    rescue => e
      Rails.logger.error "Ошибка подключения к Firebase: #{e.message}"
      flash[:error] = "Произошла ошибка при загрузке данных."
    end

    redirect_to root_path if flash[:error].present?

    # Получение сообщений пользователя из Realtime Database
    firebase_db_client = FirebaseDB.client
    messages_data = firebase_db_client.get("messages/#{user_id}")

    if messages_data.success?
      @messages = messages_data.body
    else
      flash[:error] ||= "Не удалось загрузить сообщения."
    end
  end

  def logout
    session.clear
    flash[:notice] = "Вы успешно вышли из системы."
    redirect_to root_path
  end

  private

  def translate_error(message)
    message = message.strip

    message = message.split(':').first.strip

    case message
    when "EMAIL_NOT_FOUND"
      "Электронная почта не найдена."
    when "INVALID_PASSWORD"
      "Неверный пароль."
    when "USER_DISABLED"
      "Учетная запись отключена."
    when "EMAIL_EXISTS"
      "Электронная почта уже зарегистрирована."
    when "OPERATION_NOT_ALLOWED"
      "Операция не разрешена. Обратитесь в поддержку."
    when "TOO_MANY_ATTEMPTS_TRY_LATER"
      "Слишком много попыток. Попробуйте позже."
    when "INVALID_LOGIN_CREDENTIALS"
      "Неверные учетные данные. Проверьте ваш email и пароль."
    when "INVALID_EMAIL"
      "Некорректный формат электронной почты."
    when "MISSING_PASSWORD"
      "Пароль обязателен."
    when "MISSING_EMAIL"
      "Отсутствует электронная почта."
    when "WEAK_PASSWORD"
      "Пароль должен содержать минимум 6 символов."
    else
      "Произошла неизвестная ошибка: #{message}."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def contact
    @message = Message.new
  end

  def create
    require 'firebase'


    base_uri = ENV['FIREBASE_BASE_URI']
    private_key_json = File.read(ENV['FIREBASE_CREDENTIALS'])
    firebase = Firebase::Client.new(base_uri, private_key_json) 

    data = {
     name: params[:name],
     email: params[:email],
     subject: params[:subject],
     body: params[:body]
    }
 
    response = firebase.push("messages", data)
 
    if response.success?
      flash[:notice] = "Ваше сообщение отправлено!"
    else
      flash[:alert] = "Произошла ошибка при отправке сообщения."
    end
      redirect_to contact_path
    rescue => e
      logger.error "Ошибка при отправке данных в Firebase: #{e.message}, #{e.backtrace.join("\n")}"
      flash[:alert] = "Произошла ошибка. Попробуйте позже."
      redirect_to contact_path
  end

  private

  def message_params
    params.permit(:name, :email, :subject, :body)
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
  end
end

app/controllers/legends_controller.rb
class LegendsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/contacts/contact.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Контактная форма</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'contact', media: 'all' %>
</head>
<body>
<div class="form-container">
  <% if flash[:notice] %>
    <div class="flash notice"><%= flash[:notice] %></div>
  <% elsif flash[:alert] %>
    <div class="flash alert"><%= flash[:alert] %></div>
  <% end %>

  <h2>Свяжитесь с нами</h2>
<%= form_with url: submit_message_path, method: "post", local: true do |f| %>
  <div class="input-group">
    <%= f.label :name, "Имя:" %>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="input-group">
    <%= f.label :email, "Почта:" %>
    <%= f.email_field :email, required: true %>
  </div>
  <div class="input-group">
    <%= f.label :subject, "Тема:" %>
    <%= f.text_field :subject %>
  </div>
  <div class="input-group">
    <%= f.label :body, "Сообщение:" %>
    <%= f.text_area :body, required: true %>
  </div>
  <%= f.submit "Отправить сообщение", class: "submit-btn" %>
<% end %>


</div>
</body>
</html>

app/views/genres/index.html.erb
<h1>Genres#index</h1>
<p>Find me in app/views/genres/index.html.erb</p>

app/views/home/genres.html.erb
<head>
  <%= stylesheet_link_tag 'genres', media: 'all' %>
</head>

<main>
  <h2 class="aligncenter">Жанры мировой музыки</h2>
  <table class="music-table">
    <thead>
    <tr>
      <th>Жанр</th>
      <th>Страна</th>
      <th>Описание</th>
    </tr>
    </thead>
    <tbody>
    <% @genres.each do |genre| %>
      <tr>
        <td><a href="<%= genre.link %>" target="_blank"><%= genre.name %></a></td>
        <td><%= genre.country %></td>
        <td><%= genre.description %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</main>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Главная страница</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="worldmusic.css">
  <link rel="icon" href="images/favicon.ico" type="image/x-icon">
  <%= stylesheet_link_tag 'home', media: 'all' %>
</head>
<body>
<div id="wrapper">
  <br>
  <h2 class="aligncenter">Откройте для себя звуки мира</h2>
  <div id="content">
    <main>
      <h3>Откройте для себя музыку со всех уголков мира</h3>
      <p>Присоединяйтесь к нам в необыкновенное музыкальное путешествие! Мы отмечаем яркое разнообразие мировой музыки, ритмы и мелодии со всего мира. От энергичных ритмов афробита до умиротворяющих мелодий классического ситара, наш сайт - это великолепный репертуар для музыкальных исследований. От музыкального энтузиаста до новичка, изучающего новые жанры, вы откроете для себя богатое многообразие песен, которые стирают границы и культуры. Погрузимся в это путешествие, полное открытий и вдохновения!</p>
   <div class="container">
  <div class="gridcontainer">
    <div class="griditem">
      <%= image_tag 'headphonejoy1.jpg', alt: 'Счастливый ребенок с наушниками' %>
      <p>Изображение от andreas на Freepik</p>
    </div>
    <div class="griditem">
      <%= image_tag 'headphonejoy2.jpg', alt: 'Еще один счастливый ребенок с наушниками' %>
      <p>Изображение от master1305 на Freepik</p>
    </div>
    <div class="griditem">
      <%= image_tag 'avicii.jpg', alt: 'Выступление Avicii' %>
      <p>Фотография Майк Лоури</p>
    </div>
    <div class="griditem">
      <%= image_tag 'bobmarley1978.jpg', alt: 'Боб Марли поет на сцене' %>
      <p>Фото из архива Халтон</p>
    </div>
  </div>
  <aside class="featured-artist">
    <h3>Избранный мировой артист</h3>
    <%= image_tag 'michaeljackson.jpeg', alt: 'Избранный артист' %>
    <p class="right">Фотография Фил Дент/Редфернс</p>
    <p>Мы отмечаем влияние Майкла Джексона на музыку через жанры и поколения. Его богатая карьера продолжает вдохновлять мир.&nbsp;<a href="https://ru.wikipedia.org/wiki/%D0%94%D0%B6%D0%B5%D0%BA%D1%81%D0%BE%D0%BD,_%D0%9C%D0%B0%D0%B9%D0%BA%D0%BB" target="_blank">Узнать больше</a></p>
  </aside>
</div>
      <iframe width="560" height="315" src="https://www.youtube.com/embed/7dEBbXe5FcI?si=dtzwCrmVCXXhrTY4" title="YouTube видеоплеер" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
      <p class="right">Несколько слов о Майкле.</p>
    </aside>
  </div>
  <p class="mainaligncenter">Начните свое музыкальное приключение через богатые страницы жанров и легенд, которые ждут именно вас!</p>
  <br>
</div>
</body>
</html>

app/views/home/legends.html.erb
<head>
  <%= stylesheet_link_tag 'legends.css', media: 'all' %>
</head>

<main>
  <h2 class="aligncenter">Легенды мировой музыки</h2>
  <table class="music-table">
    <thead>
    <tr>
      <th>Имя</th>
      <th>Жанр</th>
      <th>Эра</th>
      <th>Страна</th>
      <th>Описание</th>
    </tr>
    </thead>
    <tbody>
    <% @legends.each do |legend| %>
      <tr>
        <td><a href="<%= legend.link %>" target="_blank"><%= legend.name %></a></td>
        <td><%= legend.genre %></td>
        <td><%= legend.era %></td>
        <td><%= legend.country %></td>
        <td><%= legend.description %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Музыка мира</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'snow', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>

<% if flash[:notice] || flash[:error] %>
  <div class="flash-message <%= flash[:notice] ? 'notice' : 'error' %>">
    <p><%= flash[:notice] || flash[:error] %></p>
  </div>
<% end %>

<header class="headercontainer">
  <div class="header-logo">
    <div class="header-logo-text">
      <%= image_tag 'sitelogo.png', alt: 'Логотип сайта', id: 'logo-image', class: 'logo' %>
    </div>
  </div>
  <div class="header-title">
    <h1>Музыка мира</h1>
  </div>
  <nav class="header-nav">
    <ul>
      <li><%= link_to 'Главная', root_path %></li>
      <li><%= link_to 'Жанры', genres_path %></li>
      <li><%= link_to 'Легенды', legends_path %></li>
      <li><%= link_to 'Контакты', contact_path %></li>
    </ul>
  </nav>

  <!-- Блок для входа/регистрации -->
 <div class="header-account">
  <% if session[:user_id] %>
    <%= link_to 'Личный кабинет', dashboard_path, class: 'header-btn' %>
    <%= link_to 'Выйти', logout_path, method: :post, class: 'header-btn' %>
  <% else %>
    <%= link_to 'Войти', login_path, class: 'header-btn' %>
  <% end %>
</div>
</header>


<!-- Контейнер для снега -->
<div class="snow-container"></div>

<%= yield %>

<footer class="footer">
  <p>&copy; 2024 Музыка со всего мира | Все права защищены</p>
</footer>
</body>
</html>

app/views/users/dashboard.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="worldmusic.css">
  <link rel="icon" href="images/favicon.ico" type="image/x-icon">
  <%= stylesheet_link_tag 'dashboard', media: 'all' %>
  <title>Личный кабинет</title>
</head>
<body>
  <div class="container">
    <div class="user-info">
    <%# <h2>Добро пожаловать, <%= user['name'] %>
      <p>Email: <%= user['email'] %></p>
    </div>

    <div class="messages">
      <h3>Ваши сообщения:</h3>
      <% messages.each do |message| %>
        <div class="message-item" onclick="alert('<%= message['content'] %>')">
          <span class="message-topic">Тема: <%= message['topic'] %></span>
          <span class="message-sender">От: <%= message['sender'] %></span>
        </div>
      <% end %>
    </div>
  </div>
</body>
</html>
 <!-- Верхняя часть с данными пользователя -->
    <%# <div class="user-info">
      <h2><%= @user.name %</h2>
      <p>Email: <%= @user.email %</p>
    </div>

    <!-- Нижняя часть с сообщениями -->
    <div class="messages">
      <% @messages.each do |message| %
        <div class="message-item" onclick="location.href='<%= message_path(message) %'">
          <span class="message-topic"><%= message.topic %</span>
          <span class="message-sender">От: <%= message.sender_name %</span>
        </div>
      <% end %
    </div> %>

app/views/users/login.html.erb
<link rel="stylesheet" href="worldmusic.css">
<link rel="icon" href="images/favicon.ico" type="image/x-icon">
<%= stylesheet_link_tag 'login', media: 'all' %>
<div class="form-wrapper">
  <div class="form-container">
    <h2>Вход</h2>

    <%= form_with url: login_path, local: true, method: :post do %>
      <div class="input-group">
        <%= label_tag "email", "Почта" %>
        <%= email_field_tag "email", nil, class: "form-input" %>
      </div>

      <div class="input-group">
        <%= label_tag "password", "Пароль" %>
        <%= password_field_tag "password", nil, class: "form-input" %>
      </div>

      <%= submit_tag "Войти", class: "submit-btn" %>
    <% end %>

    <%= link_to 'Зарегистрироваться', signup_url, class: 'register-link' %>
  </div>
</div>

app/views/users/new.html.erb
<h2>Login</h2>

<%= form_with url: signup_path, local:true, method: :post do %>
  <div>
    <%= label_tag "email" %>
    <%= email_field_tag "email", nil %>

    <%= label_tag "password" %>
    <%= password_field_tag "password", nil %>

    <%= submit_tag "Login" %>
  </div>

<% end %>

<br/>
<br/>
<br/>

<%= link_to 'Register', signup_url %>

app/views/users/signup.html.erb
<link rel="stylesheet" href="worldmusic.css">
<link rel="icon" href="images/favicon.ico" type="image/x-icon">
<%= stylesheet_link_tag 'signup', media: 'all' %>
<div class="form-wrapper">
<div class="form-container">
<h2>Регистрация</h2>

<%= form_with url: signup_path, local:true, method: :post do %>
 <div class="input-group">
    <%= label_tag "Почта" %>
    <%= email_field_tag "email", nil, class: "form-input"%>
 </div>

 <div class="input-group">
    <%= label_tag "Пароль" %>
    <%= password_field_tag "password", nil, class: "form-input" %>
 </div>

    <%= submit_tag "Зарегистрироваться", class: 'register-link' %>
  </div>

<% end %>

<!--<h2>Login</h2>-->

<%#= form_with url: login_path, local:true, method: :post do %>
<!--  <div>-->
    <%#= label_tag "email" %>
    <%#= email_field_tag "email", nil %>

    <%#= label_tag "password" %>
    <%#= password_field_tag "password", nil %>

    <%#= submit_tag "Login" %>
<!--  </div>-->

<%# end %>

<!--<br/>-->
<!--<br/>-->
<!--<br/>-->

<%#= link_to 'Register', signup_url %>